apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJkbk5sZG05c2IyUXRibWxyYVhScGJqcG5hSEJmZG1OTk1IRXhhR2hQYkdVMFJsTlphekJDWVRSUGN6ZHJhalZRZFd0Sk1WbGhVSE50IgogICAgICAgIH0KICAgIH0KfQ==
type: kubernetes.io/dockerconfigjson
