FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8000

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/microservices/proxy/CinemaAbyss.Proxy/CinemaAbyss.Proxy.csproj", "src/microservices/proxy/CinemaAbyss.Proxy/"]
RUN dotnet restore "./src/microservices/proxy/CinemaAbyss.Proxy/CinemaAbyss.Proxy.csproj"
COPY . .
WORKDIR "/src/src/microservices/proxy/CinemaAbyss.Proxy"
RUN dotnet build "./CinemaAbyss.Proxy.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./CinemaAbyss.Proxy.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CinemaAbyss.Proxy.dll"]